-- begin CUBASDBMT_TENANT
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID)^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_TENANT_ID on CUBASDBMT_TENANT (TENANT_ID, DELETE_TS)^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_ACCESS_GROUP_ID on CUBASDBMT_TENANT (ACCESS_GROUP_ID, DELETE_TS) ^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_ADMIN_ID on CUBASDBMT_TENANT (ADMIN_ID, DELETE_TS) ^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_NAME on CUBASDBMT_TENANT (NAME, DELETE_TS) ^
-- end CUBASDBMT_TENANT
