-- begin CUBASDBMT_TENANT
alter table CUBASDBMT_TENANT add constraint FK_SDBMT_TENANT_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
alter table CUBASDBMT_TENANT add constraint FK_SDBMT_TENANT_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID)^
create unique index IDX_SDBMT_TENANT_UK_TENANT_ID on CUBASDBMT_TENANT (TENANT_ID, DELETE_TS)^
create unique index IDX_SDBMT_TENANT_UK_ADMIN_ID on CUBASDBMT_TENANT (ADMIN_ID, DELETE_TS)^
create unique index IDX_SDBMT_TENANT_UK_ACCGR_ID on CUBASDBMT_TENANT (ACCESS_GROUP_ID, DELETE_TS)^
create unique index IDX_SDBMT_TENANT_UK_NAME on CUBASDBMT_TENANT (NAME, DELETE_TS)^
-- end CUBASDBMT_TENANT