-- begin CUBASDBMT_TENANT
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ON_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ON_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID)^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_ACCESS_GROUP_ID on CUBASDBMT_TENANT (ACCESS_GROUP_ID) ^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_ADMIN_ID on CUBASDBMT_TENANT (ADMIN_ID) ^
create unique index IDX_CUBASDBMT_TENANT_UNIQ_NAME on CUBASDBMT_TENANT (NAME) ^
-- end CUBASDBMT_TENANT
