-- begin SDBMT_TENANT
alter table SDBMT_TENANT add constraint FK_SDBMT_TENANT_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
create unique index IDX_SDBMT_TENANT_UNIQ_TENANT_ID on SDBMT_TENANT (TENANT_ID) ^
create unique index IDX_SDBMT_TENANT_UNIQ_ACCESS_GROUP_ID on SDBMT_TENANT (ACCESS_GROUP_ID) ^
-- end SDBMT_TENANT
