-- begin CUBASDBMT_TENANT
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
alter table CUBASDBMT_TENANT add constraint FK_CUBASDBMT_TENANT_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID)^
create unique index IDX_CUBASDBMT_TENANT_UK_ADMIN_ID on CUBASDBMT_TENANT (ADMIN_ID) where DELETE_TS is null ^
create unique index IDX_CUBASDBMT_TENANT_UK_ACCESS_GROUP_ID on CUBASDBMT_TENANT (ACCESS_GROUP_ID) where DELETE_TS is null ^
create unique index IDX_CUBASDBMT_TENANT_UK_NAME on CUBASDBMT_TENANT (NAME) where DELETE_TS is null ^
-- end CUBASDBMT_TENANT
